### ISSUE TITLE
Permissioned RPC endpoints

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-libp2p-gorpc#35]
This is the initial write up for fine-grained authorization in the RPC Endpoints.

Currently, we do not support any authorization mechanisms for RPC endpoints. We would like to create an
authorization mechanism based on Peer IDs (which are already authenticated) that allows to:

* Allow some peers IDs to use certain Service/Methods
* Disallow some peer IDs to use certain Service/Methods (while allowing the rest). Blacklists should have priority over whitelists.

Since it is easy to split a Service into multiple ones, we might discuss if simply we allow/disallow access per/service, and let the users of the library come up with their permission scheme on top of that, by subdividing their services (i.e. wrapping them).

The whole thing should be easily configurable with a configuration option (as will be introduced by #34 ).

I don't know if it's best to have something like:

```
{
  "default": "disallow",
  "peerid": {
    "allow": ["svc.method1", "svc.method2"],
  }
}
```
(map peers to services)

or 

```
{
  "default": "disallow",
  "svc.method1": {
    "allow": ["peerid1"]
  }
}
```
(map services to peers)

or some other way.

In cluster we will want RPC endpoints mostly closed by default, with a set of trusted peers that can access just a small subset of them.

**Comment by lanzafame** [comment]
Some thoughts/questions I had after reading/thinking through this yesterday.

I have a preference for a whitelist system as it is simpler to reason and it covers most of the permissioning cases that we need, see this [stackoverflow answer](https://stackoverflow.com/a/504424/3299523). Also, if we have a whitelist system, the uses for a blacklist system are reduced to just a blocklist, where we want to block abusive peers. And if we want to open up a service to the world, we can just explicit use a wildcard value for that service.

Regarding how we map the permissions, I think that `service: [peers]` is the better, though being able to define scopes would be great, so 
```
admin := [service1.{write,read},service2.{write,read}]
user := [service1.read, service2.read]
```
and then the mapping file would be
```
admin: [peerid1]
user: [peerid1, peerid2, ...]
```

The other big questions I have surrounds registration or bootstrapping of new peers. 

How this would work with bi-directional streams between a more permissioned peer and less permissioned peer (this may not have an issues but without diving into it feels like it may). 

How do we integrate this system with potentially existing user/role systems of systems using gorpc, i.e. ipfs-cluster.

And in a ipfs-cluster specific case, for composite and federated clusters, it won't be just one peer that needs to be authenticated but the cluster, should we be giving the cluster an id as well?

**Comment by hsanjuan** [comment]
`admin := [service1.{write,read},service2.{write,read}]`

To avoid confusion, this should say `service1.{method1,method2}`. I prefer to avoid the sugar and have ["service1.method1", "service1.method2"..]` etc. An RPC stream is always going to be read/write on both ends.

> I have a preference for a whitelist system

It's not so hard to have both I think, but yes, whitelist is the most useful.

> How do we integrate this system with potentially existing user/role systems of systems using gorpc, i.e. ipfs-cluster.

This is completely separate from any other user authentication and plays no role in federated clusters. This is about permissions for peer IDs. Composite and federated clusters don't use the RPC APIs. The "users" of the RPC APIs are the other cluster peers.

**Comment by hsanjuan** [comment]
> How this would work with bi-directional streams between a more permissioned peer and less permissioned peer (this may not have an issues but without diving into it feels like it may).

Note that in RPC call there is always a client (making the call) and a server (executing it). We are adding permissions to the server part. There is not  a `less permissioned` peer in the play, the client has no permissions, it can try to call whatever it wants.

**Comment by hsanjuan** [comment]
For an example on how to apply blacklist/whitelists properly: https://github.com/libp2p/go-libp2p-gorpc/issues/35

**Comment by kishansagathiya** [comment]
Some relevant discussion at https://github.com/ipfs/ipfs-cluster/pull/467

**Comment by kishansagathiya** [comment]
I have put some questions on the RFC for the collaborative pinsets. After that I will write down what our(IPFS-Cluster's) exact usecase is and sample configuration based on that. Initial discussion seems to take a bit generic approach, but I agree with `default: disallow` and having wildcards and scopes. After that we can try to generalize that.
@hsanjuan @lanzafame Does that sound good? 

From what I understand so far, we will need two scopes, one for members of trusted peerset and one for those which are not trusted.

**Comment by hsanjuan** [comment]
This should have a more general approach than the specific use-case needed by Cluster. I remember a standup where we discussed that we should just allow passing in an `Authorize(peer, service, method) bool` function to the server and defer the implementation details to the users of the library. @lanzafame right?

**Comment by kishansagathiya** [comment]
When you say peer ids are authenticated, you mean using https://github.com/libp2p/go-libp2p-secio, right?

Somehow this issue seems rather simple to me. All peers would have a map, in which peer id is the key and value would be methods allowed for a service. 
```
{ 
"key": "peerid",
"value": {
                "servicename": "ServiceXyz",
                 "allowed_methods": {"MethodA", "MethodB"},
              }
}
```
Everytime request comes we will check through this map to see if it is allowed. 
This config would be on a particular peer's node. As in peer would modify based on what other peers it want to trust. Thoughts?

Cluster specific:
The cluster should not be able to modify this file. 
With that trusted peerset would not be a particular set that controls the entire network, but it would be defined by the peer based on which other peers it chooses to trust and how much. Does that sound good?

**Comment by lanzafame** [comment]
They are authenticated by the fact that a peer id is a public key of a key pair that backs the encrypted connection between the peer.

Regarding the data structure, I think it would make sense to concatenate the service name and method name, i.e. `ServiceName.MethodA`, so that we can store the peer ids and their allowed methods as follows:
```go
// It is kind of ugly to initialize...
whitelist := map[peer.ID]map[string]bool{
    "QmXhzEc7WYu6FCfAx8hnJchqVtLGBMmD4i1NoSby37V8Fv": map[string]bool{
        "RPCAPI.Pin": true,
        "RPCAPI.ID": true,
   },
}

func (server *Server) handle(s *streamWrap) error {
	var err error
	var svcID ServiceID
	var argv, replyv reflect.Value
	ctx := context.Background()

	err = s.dec.Decode(&svcID)
	if err != nil {
		return newServerError(err)
	}
       
        // but it makes access nice and it will be better once `ServiceID` has a `.Pretty()` method
	if !whitelist[s.stream.Conn().RemotePeer()][svcID.Name+"."+svcID.Method] {
          return 
        }
....
```

**Comment by hsanjuan** [comment]
Still think this should just be:

```go
func (server *Server) handle(s *streamWrap) error {
	var err error
	var svcID ServiceID
	var argv, replyv reflect.Value
	ctx := context.Background()

	err = s.dec.Decode(&svcID)
	if err != nil {
		return newServerError(err)
	}
       
        // but it makes access nice and it will be better once `ServiceID` has a `.Pretty()` method
	if s.authorize != nil && !s.authorize(s.stream.Conn().RemotePeer(), svcID.Name, svcID.Method] {
          return 
        }
....
```

and we'll deal with whitelist format in `ipfs-cluster` (possibly doing it internally like this but hiding it from the user and having preset `map[string]bool` for different capabilities).

**Comment by kishansagathiya** [comment]
> I think it would make sense to concatenate the service name and method name, i.e. `ServiceName.MethodA`

I don't see much benefit from this, but I can live with that format. However I don't think we should use this format in the config.

**Comment by hsanjuan** [comment]
> > I think it would make sense to concatenate the service name and method name, i.e. `ServiceName.MethodA`
> 
> I don't see much benefit from this, but I can live with that format. However I don't think we should use this format in the config.

That format allows matching a service+method on a single step by looking it up in the map which is directly convertable to json if need be. Your format requires parsing nested maps, looping a slice to check for a method name after accessing `value` field. Then it's not even clear how multiple service names would work (more looping?). So yes, there is great benefit in @lanzafame 's format.

**Comment by kishansagathiya** [comment]
@hsanjuan Yeah, you are right I think I made a mistake while writing the pattern(my bad), that array should have been a map.

**Comment by kishansagathiya** [comment]
```go
	if s.authorize != nil && !s.authorize(s.stream.Conn().RemotePeer(), svcID.Name, svcID.Method) {
          return 
        }
```
Shouldn't authorize be a method of the server and not streamWrap?

**Comment by lanzafame** [comment]
@kishansagathiya Yes, I believe so. @hsanjuan Could you clarify please?

**Comment by hsanjuan** [comment]
yes yes, `server` sorry. I fixed it.

**Comment by Kubuxu** [comment]
I know I'm late, but please look at Kubernetes model of API authentication and authorisation.

**Comment by Kubuxu** [comment]
And this: https://kubernetes.io/docs/reference/access-authn-authz/authorization/

**Comment by Kubuxu** [comment]
In general, kubernetes splits the process into two parts:establishing who you are and if you should have access at all (Authentication); giving you access to specific endpoints (Authorization).

**Comment by hsanjuan** [comment]
Yes, but authentication is provided by libp2p because of authenticated streams. and authorization here is simply handed off to a third party. The Kubernetes approach is a good source to think about our rest api though.
