### ISSUE TITLE
Using goprpc to wrap a standalone non-p2p http server into a p2p host.

### ISSUE THREAD

**Issue by askquestions** [libp2p/go-libp2p-gorpc#84]
In examples/ping.go, the main server functionality is quoted as follows.

func (t *PingService) Ping(ctx context.Context, argType PingArgs, replyType *PingReply) error {
	log.Println("Received a Ping call")
	replyType.Data = argType.Data
	return nil
}

Is it possible that you provide an example of rewriting func Ping to run a non-p2p standalone server program which runs forever until being closed?

I want to see how goprpc can be used to wrap a standalone non-p2p http server into a p2p host.

Thanks.

**Comment by hsanjuan** [comment]
Are you perhaps interested in https://github.com/libp2p/go-libp2p-http ?
