### ISSUE TITLE
Tutorial for non-client/server peer-to-peer usage

### ISSUE THREAD

**Issue by leighmcculloch** [libp2p/go-libp2p-gorpc#88]
I've been exploring using this module in a p2p use case for the convenience of request and response.

The repo has one example, the ping example, which demonstrates a client and server arrangement where the relationship between both parties is asymmetrical. There is a ping server and a ping client, and the actions that each can take are significantly different. Only the client can initiate an action.

It would be really helpful if the repo contained a tutorial demonstrating how to do rpc using this module in a p2p arrangement where the participants are symmetrical, and once a connection is established both participants may initiate and there is little or no distinction between who the client and server is.

If that isn't the usecase of this library, I apologize, and I am in the wrong place 😄. If I'm trying using the wrong libp2p Go library, I'd appreciate being pointed in the right direction.

**Comment by hsanjuan** [comment]
Just create two clients with server and you're good to go: https://pkg.go.dev/github.com/libp2p/go-libp2p-gorpc?utm_source=godoc#NewClientWithServer

**Comment by leighmcculloch** [comment]
I think the scenario I'm suggesting a tutorial for was misundersrood. A client would be connecting to a server, then client and server could rpc to each other, not only the client could rpc to the server.

>NewClientWithServer takes an additional RPC Server and returns a Client which will perform any requests to itself

NewClientWithServer looks like it'd allow the server to call itself, rather than allow the server to call the connected client.

**Comment by hsanjuan** [comment]
In order for a client to receive RPCs, it needs to be a server at the same time, and vice-versa.

The network connection they use is the same.



> > NewClientWithServer takes an additional RPC Server and returns a Client which will perform any requests to itself

I have improved that doc line. It does not mean it will perform all requests to itself, it means it knows how to perform requests to itself. You can create server and client separately on each peer anyways.
